feat!: move markup to *.tsx
htmlacademy-react/668509-what-to-watch-9 pull request #7
Opened 2022-02-18 09:31 UTC by german-baranov

2022-02-18 18:19 UTC, yurylavrukhin requested changes
ты сделал намного больше, чем попросили в задании, молодец! 👏 

> пожалуй, и ее стоило разбить на более мелкие коммиты

да, стоило, не делай так больше

> в следующие разы буду лучше дробить по смыслу, если ты не против

лучше дробить по смыслу, когда ты будешь так делать, ты сам будешь лучше понимать что ты делаешь. я только за. все за

2022-02-19 00:37 UTC, german-baranov commented on project/src/components/film-list-view/film-list-view.tsx
> +    <div className="catalog__films-list">
хм. но по заданию мы берем готовую разметку и работаем с ней, как есть. считаешь, лучше изменить на более верное?

2022-02-19 00:45 UTC, german-baranov commented on project/src/components/user-block-view/user-block-view.tsx
> +  if (!isSigned)    {return (null);}
как настроить преттиер так, чтобы он не противоречил правилам линтера? они все время воюют в разные стороны

2022-02-19 00:50 UTC, german-baranov commented on project/src/components/app/app.tsx
> +  return <MainView filmList={filmList} genresList={genresList}/>;
собственно, в лекции говорилось о таком формате наименования, потому так и сделал. хотя ценности не особо, согласен. ок

2022-02-19 01:59 UTC, german-baranov commented on project/src/types/film-type.ts
> +type FilmType = {
именно файлы типов? вообще по именованиям файлов в академии конвенция через дефис, если я ничего не путаю

2022-02-19 06:49 UTC, yurylavrukhin commented on project/src/components/app/app.tsx
> +  return <MainView filmList={filmList} genresList={genresList}/>;
не является. можно по JSX скобкам `<Film/>` понять что это компонент

во всем интернете, где бы ты ни посмотрел, и во всех проектах, над которыми я работал — нигде люди не добавляют к названию названию компонентов View, или Component, потому что и так понятно

2022-02-19 07:16 UTC, yurylavrukhin commented on project/src/components/film-list-view/film-list-view.tsx
> +    <div className="catalog__films-list">
ответ лежит в предыдущем сообщении

да, конечно, это хорошая практика, раз уж ты решил отрисовать список в цикле, можно добавить семантически верные теги, это занимает минуту

это не фокус этого курса, но хорошая практика, которую я хочу чтобы ты использовал всегда, когда работаешь со списками

нужно будет сбросить дефолтные стили у `ul` добавив `ul{margin: 0; padding: 0;}` в main.css чтобы разметка выглядела как раньше

2022-02-19 07:42 UTC, yurylavrukhin commented on project/src/components/user-block-view/user-block-view.tsx
> +  if (!isSigned)    {return (null);}
мне нужно больше деталий чтобы ответить на такой широкий вопрос
- расскажи, как ты установил и настроил преттиер
- приведи пример, когда они «воюют в разные стороны», и мы рассмотрим как решить эту проблему. prettier можно настраивать конфигурационным файлом в проекте https://prettier.io/docs/en/configuration.html

2022-02-19 08:01 UTC, yurylavrukhin commented on project/src/components/logo-view/logo-view.tsx
> +type LogoViewProps = {
> при функциональном подходе предпочтительнее использовать type, тогда как interface - он все таки про классы

interface в TS — это просто описание объекта и использовать его стоит когда мы работаем с объектами.
неважно классовые компоненты мы используем или функциональные

> такую штуку, например, я не могу описать интерфейсом, верно? `FilmsListType = IFilm[]`

ага, не можешь

2022-02-19 08:10 UTC, yurylavrukhin commented on project/src/components/logo-view/logo-view.tsx
> +type LogoViewProps = {
> Я подумал, что будет логично интерфейсы называть с I, а к типам дописывать Type, так как почти сразу столкнулся с дублем имен PromoFilm - был и такой тип и компонент. Такое ощущение, что должно быть какое-то соглашение по именованию.

решить эту проблему можно переименовав тип в `PromoFilmData`

люди до нас уже много это обсуждали и тут нет правильного пути
https://www.google.com/search?q=typescript+interface+i+prefix&rlz=1C5CHFA_enTH989TH989&oq=typescript+i+inter&aqs=chrome.1.69i57j0i22i30l6j69i60.3925j0j7&sourceid=chrome&ie=UTF-8
https://github.com/Microsoft/TypeScript-Handbook/issues/121
https://stackoverflow.com/questions/31876947/confused-about-the-interface-and-class-coding-guidelines-for-typescript
https://passionfordev.com/you-dont-need-to-prefix-interfaces-in-typescript-with-i/

мне кажется без префиксов/постфиксов I, Type – ок работается и фичи делаются отлично

2022-02-19 08:13 UTC, yurylavrukhin commented on project/src/components/film-card-view/film-card-view.tsx
> +  film: FilmType;
заспредь пропы в компонент, все кроме id https://reactpatterns.com/#jsx-spread-attributes

достань id вот так, используй его как key для списка https://learn.javascript.ru/destructuring-assignment#ostatok-obekta
остальное - в компонент

2022-02-19 08:55 UTC, yurylavrukhin commented on project/src/components/user-block-view/user-block-view.tsx
> +function UserBlockView ({isSigned}: UserBlockViewProps) { // cant return null with :JSX.Element. why?
> на лекции просто нам говорили, что если ничего не нужно рендерить компонент может просто вернуть null и все будет в порядке. но тут какое-то противоречие, очевидно.

это правда, противоречие только в TS типе

> можешь подробнее рассказать о том, как можно описать?

я рассказал в предыдущих сообщении как описать, чтобы не было ошибки, и почему ты получаешь ошибку.
вот подробней https://stackoverflow.com/questions/56947690/react-component-type-in-typescript

2022-02-19 08:57 UTC, yurylavrukhin commented on project/src/types/film-type.ts
> +type FilmType = {
для типов укажем тип файла
через дефис имя файла, всё согласно конвенциям академии

тип файла укажем после точки чтобы удобней навигироваться в коде `lala.types.ts`, `lala.actions.ts`, `lala.reducer.ts`, ...

2022-02-19 09:09 UTC, yurylavrukhin commented on project/src/components/page-content-view/page-content-view.tsx
> +function PageContentView ({genresList, filmList}: SettingsType): JSX.Element {
я был сонный вчера, думаю название `Catalog` лучше
там внутри такой класс есть

2022-02-19 09:10 UTC, yurylavrukhin commented on project/src/components/movie-page-view/movie-page-view.tsx
> +      <section className="film-card film-card--full">
я не знаю зачем нужен этот див, он отличается в разных файлах, я спросил зачем он нужен у ребят которые знают проект лучше меня

давай пока просто скопируем всё что было в body, как нам сказали в задании он немного отличается в разных файлах

потом удалим если что

2022-02-19 09:25 UTC, yurylavrukhin commented on project/src/components/header/header.tsx
> +  isNavigationNeeded?: boolean;
```suggestion
  hasNavigation?: boolean;
```

2022-02-19 09:25 UTC, yurylavrukhin commented on project/src/components/app/app.tsx
>  export default App;
default -> named

2022-02-19 09:25 UTC, yurylavrukhin commented on project/src/components/movie-page-view/movie-page-view.tsx
> +      <section className="film-card film-card--full">
я передумал, давай выпилим его из приложения вообще, из `/project/` оставим только в разметке
это какой-то див из скетча

в задании сказано что мы найдём разметку/вёрстку в `/markup/`, мы её и взяли. а этот див - какой то скрытый элемент.

если вдруг он понадобится, всегда его можно взять в `/markup/`

2022-02-19 09:35 UTC, yurylavrukhin requested changes
стало лучше, спасибо 💙 

я вижу проблему 😞 
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/26966797/154795345-97a06887-d449-4b8e-b641-008f9da6283e.png">


`!` в коммит-мессадже не нужен, тут нет никаких брейкинг ченджес

2022-02-19 14:55 UTC, yurylavrukhin commented on project/src/components/film-list-view/film-list-view.tsx
> +    <div className="catalog__films-list">
давай оставим как теги есть, `div` + `article` — ок
сфокусируемся на реакте

2022-02-19 15:17 UTC, yurylavrukhin commented on project/src/components/user-block-view/user-block-view.tsx
> +  if (!isSigned)    {return (null);}
в рамках этой задачи это не важно, можешь не тратить на это время

можешь попробовать настроить в свободное время, кажется будет достаточно скачать расширение prettier в vscode и настроить formatOnSave

2022-02-19 15:19 UTC, yurylavrukhin commented on project/src/components/movie-page-view/movie-page-view.tsx
> +      <section className="film-card film-card--full">
узнал: это svg спрайт и он нужен для иконок, давай везде скопируем его из разметки в наши компоненты (он немного отличается в разных файлах, так что не копируй из одного места)

2022-02-19 15:20 UTC, yurylavrukhin commented on project/src/components/add-review-view/add-review-view.tsx
> +    <section className="film-card film-card--full">
узнал: это svg спрайт и он нужен для иконок

проверь что во всех файлах разметка скопирована верно

2022-02-20 12:26 UTC, german-baranov commented on project/src/components/film-card-view/film-card-view.tsx
> +  film: FilmType;
> достань id деструктуризацией, и используй его как key для списка

вот про это не понял. промо фильм он же не в списке, он один. я думал. key нужен только для списка из повторяюищхся компонентов

2022-02-20 12:35 UTC, german-baranov commented on project/src/components/user-block-view/user-block-view.tsx
> +function UserBlockView ({isSigned}: UserBlockViewProps) { // cant return null with :JSX.Element. why?
так и не догоняю что-то, попозже разберусь, видимо. пока оставлю без типа...

(JSX attribute) React.HTMLAttributes<HTMLDivElement>.className?: string
Тип "Element" не может быть назначен для типа "ComponentType<{}>".
  Тип "ReactElement<any, any>" не может быть назначен для типа "FunctionComponent<{}>".
    Тип "ReactElement<any, any>" не предоставляет соответствия для сигнатуры "(props: { children?: ReactNode; }, context?: any): ReactElement<any, any>".ts(2322)

2022-02-20 13:15 UTC, yurylavrukhin requested changes
Компоненты — топ

поправь немного, и давай мёрджить! 

если хочешь описывать всё состояние приложения одним объектом — ок, но переименуй settings во что-то другое, например AppStore, settings — это очень странное название для состояния приложения

2022-02-20 13:15 UTC, yurylavrukhin commented on project/src/components/films/films-list.tsx
> +          <Film key={film.id} {...film}/>
в компонент не нужно прокидывать id
не знаю почему TS это разрешает

2022-02-20 13:15 UTC, yurylavrukhin commented on project/src/types/film.type.ts
> +export interface IPromoFilm extends IFilm{
назови эти файлы с `.types`, тут же несколько типов, а не один

2022-02-20 13:40 UTC, yurylavrukhin requested changes

2022-02-20 13:40 UTC, yurylavrukhin commented on project/src/index.tsx
> +const settings: IAppStore = {
здесь

2022-02-20 13:40 UTC, yurylavrukhin commented on project/src/types/appstore.type.ts
> +import { IFilm, IPromoFilm } from './film.types';
`.types.ts`

2022-02-20 14:00 UTC, merged